name: Discord Pull Request Notification
on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  notify-discord:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Notifying Discord with Node.js
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_USERNAME: ${{ github.event.pull_request.user.login }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
          AUTHOR_AVATAR: ${{ github.event.pull_request.user.avatar_url }}
          CHANGED_FILES: ${{ github.event.pull_request.changed_files }}
          ADDITIONS: ${{ github.event.pull_request.additions }}
          DELETIONS: ${{ github.event.pull_request.deletions }}
        run: |
          node -e '
            const https = require("https");
            const url = new URL(process.env.DISCORD_WEBHOOK);
          
            // Process PR body - replace checkboxes with emojis
            let processedBody = process.env.PR_BODY || "";
            processedBody = processedBody.replace(/\[x\]/g, "✅");
            processedBody = processedBody.replace(/\[ \]/g, "❌");
          
            const data = JSON.stringify({
              embeds: [{
                title: "🚀 New Update Deployed",
                description: process.env.PR_TITLE,
                url: process.env.PR_URL,
                color: 5814783,
                fields: [
                  {
                    name: "📝 Description",
                    value: process.env.PR_BODY 
                  },
                  {
                    name: "👨‍💻 Author",
                    value: process.env.PR_USERNAME
                  },
                  {
                    name: "📊 Changes",
                    value: `**${process.env.CHANGED_FILES}** files changed with **+${process.env.ADDITIONS}** additions and **-${process.env.DELETIONS}** deletions`
                  }
                ],
                thumbnail: {
                  url: process.env.AUTHOR_AVATAR
                },
                footer: {
                  text: `PR #${process.env.PR_NUMBER} merged to main branch`
                }
              }]
            });
          
            const options = {
              hostname: url.hostname,
              path: url.pathname + url.search,
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                "Content-Length": data.length
              }
            };
          
            const req = https.request(options, (res) => {
              console.log(`Status: ${res.statusCode}`);
              res.on("data", (chunk) => console.log(chunk.toString()));
            });
          
            req.on("error", (e) => console.error(e));
            req.write(data);
            req.end();
          '
